### ISSUE TITLE
Use gist-embed script

### ISSUE THREAD

**Issue by shivapoudel** [claudiosmweb/gist-github-shortcode#4]
@claudiosmweb this plugin currently supports only specific filename for gist id. If possible please use [gist-embed](https://github.com/blairvanderhoof/gist-embed/) script and let us allow to highlight the lines, hide the footer and line number. Docs: http://blairvanderhoof.com/gist-embed/

**Comment by claudiosanches** [comment]
Nop, I prefer use the official code.
